name: 'publish'

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: npm install -g pnpm && pnpm install # change this to npm or pnpm depending on which one you use

      - name: Install GitHub CLI on macOS
        if: runner.os == 'macOS'
        run: brew install gh

      - name: Install GitHub CLI on Windows
        if: runner.os == 'Windows'
        run: choco install gh

      - name: Download FastAPI Binary
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          gh auth login --with-token <<< $GH_PAT
          LATEST_RELEASE=$(gh release view --repo KGESH/trading_bot_backend --json tagName -q '.tagName')
          echo "Downloading assets for release $LATEST_RELEASE..."
          gh release download $LATEST_RELEASE --repo KGESH/trading_bot_backend --pattern "*${{ matrix.platform }}*" --dir ./external/backend/
          echo "Downloaded files:"
          ls -la ./external/backend/

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
